apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jaeger_operator.DeploymentName" . }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: jaeger-sa